// クリップボード経由で貼り付け (⌘V を送る)、少し後に元の内容 (画像なども含む全形式) を戻す。
// - 貼り付け用のテキストはこの Mac だけに置く (ユニバーサルクリップボードで他の端末に送らない)
// - クリップボード管理アプリには一時的な内容だと伝える (nspasteboard.org の目印)
// - パスワード管理アプリがコピーした内容は復元しない (自動消去を無効にしてしまうため)
// - 復元待ちの間に別のものがコピーされたら、上書きしない
import AppKit
import CoreGraphics

final class Paster {
    var restoreEnabled = ProcessInfo.processInfo.environment["JPD_RESTORE"] != "0"
    var restoreDelay = Double(ProcessInfo.processInfo.environment["JPD_RESTORE_DELAY"] ?? "") ?? 1.5
    private let pb = NSPasteboard.general
    private let transientTypes = ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        .map { NSPasteboard.PasteboardType($0) }
    private let secretTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                                            "org.nspasteboard.AutoGeneratedType"]
    private var saved: [[NSPasteboard.PasteboardType: Data]]?
    private var ourCount = -1
    private var generation = 0
    private var pendingRestore: DispatchWorkItem?
    private var snapshotBusy = false
    private let snapshotQueue = DispatchQueue(label: "jp-dictate.snapshot")

    /// メインスレッドから呼ぶ
    func paste(_ text: String) {
        let pending = pendingRestore != nil
        pendingRestore?.cancel()
        pendingRestore = nil
        // 復元待ちの間に別のものがコピーされていたら、それを新しく保存し直す
        if restoreEnabled && (!pending || pb.changeCount != ourCount) {
            saved = boundedSnapshot()
            if let s = saved, s.contains(where: { $0.keys.contains { secretTypes.contains($0.rawValue) || $0.rawValue.hasPrefix("com.agilebits") } }) {
                saved = nil
            }
        }
        generation += 1
        write(text)
        sendCommandV()
        guard restoreEnabled, saved != nil else { return }
        let gen = generation
        let work = DispatchWorkItem { [weak self] in self?.restore(gen) }
        pendingRestore = work
        DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay, execute: work)
    }

    /// 貼り付けずにクリップボードに入れるだけ (元の内容は戻さない)
    func copyOnly(_ text: String) {
        pendingRestore?.cancel()
        pendingRestore = nil
        saved = nil
        generation += 1
        write(text)
    }

    /// 終了直前に復元待ちがあれば、待たずに戻しておく
    func flush() {
        guard let work = pendingRestore else { return }
        work.cancel()
        restore(generation)
    }

    private func write(_ text: String) {
        pb.prepareForNewContents(with: .currentHostOnly)
        pb.setString(text, forType: .string)
        for t in transientTypes { pb.setData(Data(), forType: t) }
        ourCount = pb.changeCount
    }

    private func restore(_ gen: Int) {
        pendingRestore = nil
        guard gen == generation, let items = saved else { return }
        saved = nil
        guard pb.changeCount == ourCount else { return }  // 貼り付けの後に別のものがコピーされていた
        pb.prepareForNewContents(with: .currentHostOnly)
        let objs: [NSPasteboardItem] = items.map { d in
            let item = NSPasteboardItem()
            for (t, data) in d { item.setData(data, forType: t) }
            return item
        }
        if !objs.isEmpty { pb.writeObjects(objs) }
    }

    /// コピー元のアプリが固まっていると保存が終わらないので、0.25 秒で諦める (その回は復元しない)
    private func boundedSnapshot() -> [[NSPasteboard.PasteboardType: Data]]? {
        if snapshotBusy { return nil }
        snapshotBusy = true
        var result: [[NSPasteboard.PasteboardType: Data]]?
        let done = DispatchSemaphore(value: 0)
        let board = pb
        snapshotQueue.async {
            let items = (board.pasteboardItems ?? []).map { item -> [NSPasteboard.PasteboardType: Data] in
                var d: [NSPasteboard.PasteboardType: Data] = [:]
                for t in item.types { if let data = item.data(forType: t) { d[t] = data } }
                return d
            }
            result = items
            done.signal()
            DispatchQueue.main.async { self.snapshotBusy = false }
        }
        return done.wait(timeout: .now() + 0.25) == .success ? result : nil
    }

    private func sendCommandV() {
        let src = CGEventSource(stateID: .privateState)
        for keyDown in [true, false] {
            let e = CGEvent(keyboardEventSource: src, virtualKey: 9 /* V */, keyDown: keyDown)
            e?.flags = .maskCommand
            e?.post(tap: .cghidEventTap)
        }
    }
}
